global_planning_node:
  ros__parameters:
    "map/resolution": 0.1
    "map/z_min": -0.5
    "map/z_max": 1.0
    "planning/step_size": 0.2
    "planning/h_surf_car": 0.5
    "planning/radius_fit_plane": 0.2
    "planning/w_flatness": 3000.0
    "planning/w_slope": 0.3
    "planning/w_sparsity": 0.2
    "planning/w_fit_plane": 0.3
    "planning/ratio_max": 0.05
    "planning/ratio_min": 0.02
    "planning/conv_thre": 0.12
